use_frameworks!

target 'GlobalValueKeeper_Example' do
  pod 'GlobalValueKeeper', :path => '../'
  pod 'SiFUtilities'

  target 'GlobalValueKeeper_Tests' do
    inherit! :search_paths

    
  end
end
